CREATE TABLE FINANCE.SUBCATEGORIES
(
  ID                NUMBER(6) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME              VARCHAR2(20)        NOT NULL,
  DESCRIPTION       VARCHAR2(100),      --NULL
  CATEGORY_ID       NUMBER(6),          --NULL          
  CREATE_DATETIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,      
  UPDATE_DATETIME   TIMESTAMP,          --NULL
  CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_ID)
    REFERENCES FINANCE.CATEGORIES(ID)
    ON DELETE SET NULL
);
