CREATE TABLE FINANCE.CATEGORIES
(
  ID                    NUMBER(6) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME                  VARCHAR2(50)       NOT NULL,
  DESCRIPTION           VARCHAR2(100),     --NULL
  CREATE_DATETIME       TIMESTAMP          NOT NULL,
  UPDATE_DATETIME       TIMESTAMP          --NULL
);
