CREATE TABLE FINANCE.ITEMS
(
  ID                  NUMBER(6) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NAME                VARCHAR2(20)          NOT NULL,
  DESCRIPTION         VARCHAR2(100),        --NULL
  SUBCATEGORY_ID      NUMBER(6),            --NULL
  IS_NECESSARY        NUMBER(1) DEFAULT 0 CHECK (is_necessary IN (0, 1)),
  CREATE_DATETIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATE_DATETIME     TIMESTAMP,            --NULL
  CONSTRAINT FK_SUB_CATEGORY FOREIGN KEY (SUBCATEGORY_ID)
    REFERENCES FINANCE.SUBCATEGORIES(ID)
    ON DELETE SET NULL
);
